### ISSUE TITLE
有个方法名写错了

### ISSUE THREAD

**Issue by nebulax2014** [leaves4j/vue-easy-renderer#1]
是require('vue-easy-renderer').koaRenderer，文档里是require('vue-easy-renderer').kaoRenderer，让人误会啊-_-!!!，用vue-easy-renderer会把所有服务端信息在客户端的script里都显示出来，能不能去掉？

**Comment by leaves4j** [comment]
第一个问题已修复；
第二个问题你指的是渲染数据吧，渲染数据需要发送到客户端以便于vue使用
